M48
; DRILL file {KiCad (7.0.0)} date Fri Mar 24 12:40:31 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-03-24T12:40:31-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X113.97Y-97.46
X115.24Y-49.2
X166.04Y-64.44
X166.04Y-92.38
T0
M30
